### ISSUE TITLE
[demo] Uncaught TypeError: Cannot read property 'scheme' of null(…)

### ISSUE THREAD

**Issue by diffractometer** [foxhound87/mobx-ajv-form#128]
On the demo branch, after following instructions, I get the error `Uncaught TypeError: Cannot read property 'scheme' of null(…)`.

**Comment by foxhound87** [comment]
Please, can you provide the full error stack trace?

**Comment by diffractometer** [comment]
For sure! The error is only appearing in my console, there's no error from the command line: 

```

> mobx-react-form-demo@1.0.0 start /Users/hunterhusar/dev/sandbox/mobx-react-form--demo
> webpack-dev-server --port 8888

 http://localhost:8888/webpack-dev-server/
webpack result is served from /
content is served from /Users/hunterhusar/dev/sandbox/mobx-react-form--demo
Hash: 2220faa9c4743ca81807
Version: webpack 1.13.2
Time: 11980ms
     Asset       Size  Chunks             Chunk Names
   main.js    12.9 MB       0  [emitted]  main
index.html  351 bytes          [emitted]
chunk    {0} main.js (main) 4.82 MB [rendered]

...looks good
```

But when I open up (...) the error in the console I see:

```

localhost/:146 Uncaught TypeError: Cannot read property 'scheme' of null
    at eval (eval at <anonymous> (http://localhost:8888/main.js:4191:2), <anonymous>:146:35)
    at Array.reduce (native)
    at eval (eval at <anonymous> (http://localhost:8888/main.js:4191:2), <anonymous>:145:27)
    at wrapper (eval at <anonymous> (http://localhost:8888/main.js:4221:2), <anonymous>:607:15)
    at JSONTree.render (eval at <anonymous> (http://localhost:8888/main.js:4035:2), <anonymous>:114:59)
    at eval (eval at <anonymous> (http://localhost:8888/main.js:789:2), <anonymous>:793:21)
    at measureLifeCyclePerf (eval at <anonymous> (http://localhost:8888/main.js:789:2), <anonymous>:74:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (eval at <anonymous> (http://localhost:8888/main.js:789:2), <anonymous>:792:27)
    at ReactCompositeComponentWrapper._renderValidatedComponent (eval at <anonymous> (http://localhost:8888/main.js:789:2), <anonymous>:819:34)
    at ReactCompositeComponentWrapper.performInitialMount (eval at <anonymous> (http://localhost:8888/main.js:789:2), <anonymous>:361:30)
    at ReactCompositeComponentWrapper.mountComponent (eval at <anonymous> (http://localhost:8888/main.js:789:2), <anonymous>:257:21)
    at Object.mountComponent (eval at <anonymous> (http://localhost:8888/main.js:411:2), <anonymous>:47:35)
    at ReactDOMComponent.mountChildren (eval at <anonymous> (http://localhost:8888/main.js:759:2), <anonymous>:240:44)
    at ReactDOMComponent._createInitialChildren (eval at <anonymous> (http://localhost:8888/main.js:621:2), <anonymous>:699:32)
    at ReactDOMComponent.mountComponent (eval at <anonymous> (http://localhost:8888/main.js:621:2), <anonymous>:524:12)
    at Object.mountComponent (eval at <anonymous> (http://localhost:8888/main.js:411:2), <anonymous>:47:35)

```

after removing `node_modules` and reinstalling I see an error:

```

> fsevents@1.0.14 install /Users/hunterhusar/dev/sandbox/mobx-react-form--demo/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.0.14/fse-v1.0.14-node-v51-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.0.14 and node@7.0.0 (node-v51 ABI) (falling back to source compile with node-gyp)
  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
  COPY /Users/hunterhusar/dev/sandbox/mobx-react-form--demo/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node
  TOUCH Release/obj.target/action_after_build.stamp
mobx-react-form-demo@1.0.0 /Users/hunterhusar/dev/sandbox/mobx-react-form--demo
├─┬ babel-loader@6.2.5
│ ├─┬ loader-utils@0.2.16
│ │ ├── big.js@3.1.3
│ │ ├── emojis-list@2.1.0
│ │ └── json5@0.5.0
│ ├─┬ mkdirp@0.5.1
│ │ └── minimist@0.0.8

...looks good
```

**Comment by foxhound87** [comment]
Should be related at this issue which I opened recently on `react-json-tree`: https://github.com/alexkuz/react-json-tree/issues/56

I'm releasing a fix for `mobx-react-form-devtools` with a `react-json-tree` downgrade at version `0.9.0`. You should update it on the demo directory.  Let me know.

**Comment by foxhound87** [comment]
https://github.com/foxhound87/mobx-react-form-devtools/releases/tag/v1.0.4

**Comment by diffractometer** [comment]
@foxhound87 Awesome, I much appreciate your help, will take a look asap!

**Comment by diffractometer** [comment]
@foxhound87 that fixed it, thanks again!

**Comment by foxhound87** [comment]
@diffractometer great to hear that!
